version: "3.9"

services:

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: mern_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/realestate

  frontend:
    build: ./frontend
    container_name: mern_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: